// utils/flags.js
export const countryFlags = {
    NIEMCY: '🇩🇪',
    SZWAJCARIA: '🇨🇭',
    WĘGRY: '🇭🇺',
    SZKOCJA: '🦄',
    HISZPANIA: '🇪🇸',
    WŁOCHY: '🇮🇹',
    ALBANIA: '🇦🇱',
    CHORWACJA: '🇭🇷',
    SŁOWENIA: '🇸🇮',
    DANIA: '🇩🇰',
    SERBIA: '🇷🇸',
    ANGLIA: '☕',
    POLSKA: '🇵🇱',
    HOLANDIA: '🇳🇱',
    AUSTRIA: '🇦🇹',
    FRANCJA: '🇫🇷',
    BELGIA: '🇧🇪',
    SŁOWACJA: '🇸🇰',
    RUMUNIA: '🇷🇴',
    UKRAINA: '🇺🇦',
    TURCJA: '🇹🇷',
    GRUZJA: '🇬🇪',
    PORTUGALIA: '🇵🇹',
    CZECHY: '🇨🇿',
};
